[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

# Compilation
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 5_000
via_ir = false

[fuzz]
runs = 256

[fmt]
line_length = 80
int_types = "short"
number_underscore = "thousands"
ignore = ['src/generated/*', 'src/modules/fundingManager/bondingCurve/formulas/*']

[profile.ci]
fuzz = { runs = 1_024 }
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
